### ISSUE TITLE
Неправильный объем котировки

### ISSUE THREAD

**Issue by h0tc0d3** [StockSharp/Qsh2Bin#2]
При обработке этого файла ftp://athistory.zerich.com/2015-08-18/RTS-9.15.2015-08-18.OrdLog.qsh
Вылетает ошибка. Опция конвертации ордер лога в стакан включена. Нельзя ли добавить игнорирование ошибки и перейти к следущему кадру qsh файла?
> 19:05:02.547|       |Qsh2Bin   |Запуск конвертации.
> 19:05:02.571|       |Qsh2Bin   |Начата конвертация файла D:\Logs\RTS\RTS-12.15.2015-08-18.OrdLog.qsh.
> 19:05:03.478|Error  |Qsh2Bin   |System.AggregateException: Произошла одна или несколько ошибок. ---> System.ArgumentOutOfRangeException: Неправильный объем котировки.
> Имя параметра: quotes
> Фактическое значение было -4.
>    в StockSharp.Algo.Storages.Binary.QuoteBinarySerializer.SerializeQuotes(BitArrayWriter writer, IEnumerable`1 quotes, QuoteMetaInfo metaInfo)
>    в StockSharp.Algo.Storages.Binary.QuoteBinarySerializer.OnSave(BitArrayWriter writer, IEnumerable`1 messages, QuoteMetaInfo metaInfo)
>    в StockSharp.Algo.Storages.Binary.BinaryMarketDataSerializer`2.Serialize(Stream stream, IEnumerable`1 data, IMarketDataMetaInfo metaInfo)
>    в StockSharp.Algo.Storages.MarketDataStorage`2.Save(Stream stream, IMarketDataMetaInfo metaInfo, TData[] data, Boolean isOverride)
>    в StockSharp.Algo.Storages.MarketDataStorage`2.Save(IEnumerable`1 data)
>    в StockSharp.Algo.Storages.MarketDataStorage`2.StockSharp.Algo.Storages.IMarketDataStorage.Save(IEnumerable data)
>    в StockSharp.Qsh2StockSharp.MainWindow.TryFlushData[TMessage](IStorageRegistry registry, Security security, StorageFormats format, Object arg, List`1 messages, QshReader reader) в MainWindow.xaml.cs:строка 240
>    в StockSharp.Qsh2StockSharp.MainWindow.<>c__DisplayClass16_1.<ConvertFile>b__8(Int32 key, OrdLogEntry ol) в MainWindow.xaml.cs:строка 514
>    в QScalp.History.Reader.V4.OrdLogStream.Read(Boolean push) в QScalp\Reader\V4\OrdLogStream.cs:строка 160
>    в QScalp.History.Reader.V4.QshReaderImpl.Read(Boolean push) в QScalp\Reader\V4\QshReaderImpl.cs:строка 134
>    в StockSharp.Qsh2StockSharp.MainWindow.ConvertFile(String fileName, IStorageRegistry registry, StorageFormats format, ExchangeBoard board, String securityLike, Dictionary`2 orderLog2OrderBookBuilders, Int32 orderBookMaxDepth) в MainWindow.xaml.cs:строка 557
>    в StockSharp.Qsh2StockSharp.MainWindow.<>c__DisplayClass14_0.<ConvertDirectory>b__0(String f) в MainWindow.xaml.cs:строка 217
>    в MoreLinq.MoreEnumerable.ForEach[T](IEnumerable`1 source, Action`1 action)
>    в StockSharp.Qsh2StockSharp.MainWindow.ConvertDirectory(String path, IStorageRegistry registry, StorageFormats format, ExchangeBoard board, String securityLike, Boolean multithread, Dictionary`2 orderLog2OrderBookBuilders, Int32 orderBookMaxDepth) в MainWindow.xaml.cs:строка 217
>    в StockSharp.Qsh2StockSharp.MainWindow.<>c__DisplayClass13_0.<Convert_OnClick>b__0() в MainWindow.xaml.cs:строка 172
>    в System.Threading.Tasks.Task.InnerInvoke()
>    в System.Threading.Tasks.Task.Execute()
>    --- Конец трассировки внутреннего стека исключений ---
> ---> (Внутреннее исключение #0) System.ArgumentOutOfRangeException: Неправильный объем котировки.
> Имя параметра: quotes
> Фактическое значение было -4.
>    в StockSharp.Algo.Storages.Binary.QuoteBinarySerializer.SerializeQuotes(BitArrayWriter writer, IEnumerable`1 quotes, QuoteMetaInfo metaInfo)
>    в StockSharp.Algo.Storages.Binary.QuoteBinarySerializer.OnSave(BitArrayWriter writer, IEnumerable`1 messages, QuoteMetaInfo metaInfo)
>    в StockSharp.Algo.Storages.Binary.BinaryMarketDataSerializer`2.Serialize(Stream stream, IEnumerable`1 data, IMarketDataMetaInfo metaInfo)
>    в StockSharp.Algo.Storages.MarketDataStorage`2.Save(Stream stream, IMarketDataMetaInfo metaInfo, TData[] data, Boolean isOverride)
>    в StockSharp.Algo.Storages.MarketDataStorage`2.Save(IEnumerable`1 data)
>    в StockSharp.Algo.Storages.MarketDataStorage`2.StockSharp.Algo.Storages.IMarketDataStorage.Save(IEnumerable data)
>    в StockSharp.Qsh2StockSharp.MainWindow.TryFlushData[TMessage](IStorageRegistry registry, Security security, StorageFormats format, Object arg, List`1 messages, QshReader reader) в MainWindow.xaml.cs:строка 240
>    в StockSharp.Qsh2StockSharp.MainWindow.<>c__DisplayClass16_1.<ConvertFile>b__8(Int32 key, OrdLogEntry ol) в MainWindow.xaml.cs:строка 514
>    в QScalp.History.Reader.V4.OrdLogStream.Read(Boolean push) в QScalp\Reader\V4\OrdLogStream.cs:строка 160
>    в QScalp.History.Reader.V4.QshReaderImpl.Read(Boolean push) в QScalp\Reader\V4\QshReaderImpl.cs:строка 134
>    в StockSharp.Qsh2StockSharp.MainWindow.ConvertFile(String fileName, IStorageRegistry registry, StorageFormats format, ExchangeBoard board, String securityLike, Dictionary`2 orderLog2OrderBookBuilders, Int32 orderBookMaxDepth) в MainWindow.xaml.cs:строка 557
>    в StockSharp.Qsh2StockSharp.MainWindow.<>c__DisplayClass14_0.<ConvertDirectory>b__0(String f) в MainWindow.xaml.cs:строка 217
>    в MoreLinq.MoreEnumerable.ForEach[T](IEnumerable`1 source, Action`1 action)
>    в StockSharp.Qsh2StockSharp.MainWindow.ConvertDirectory(String path, IStorageRegistry registry, StorageFormats format, ExchangeBoard board, String securityLike, Boolean multithread, Dictionary`2 orderLog2OrderBookBuilders, Int32 orderBookMaxDepth) в MainWindow.xaml.cs:строка 217
>    в StockSharp.Qsh2StockSharp.MainWindow.<>c__DisplayClass13_0.<Convert_OnClick>b__0() в MainWindow.xaml.cs:строка 172
>    в System.Threading.Tasks.Task.InnerInvoke()
>    в System.Threading.Tasks.Task.Execute()<---
> 
>

**Comment by mikasoukhov** [comment]
Попробуйте. Конечный вариант залейте как пул реквест.
