### ISSUE TITLE
Пожалуйста добавьте запись ОИ в bin

### ISSUE THREAD

**Issue by NikolaiFlyorov** [StockSharp/Qsh2Bin#3]
Добрый день, счастья, здоровья!
Вот тут пример файла QSH и его сконвертированный клон в txt + програмка для конвертации
https://cloud.mail.ru/public/CeGD/ynNt1h54D

Текстовик открыт в R, вот доказательство что ОИ там есть:
http://clip2net.com/s/3H2E6sZ

Пожалуйста сделайте, чтобы bin при конвертации содержал ОИ.

Заранее спасибо!

**Comment by eugene20237** [comment]
Поддерживаю! ОИ очень нужен. И очень странно, что его нет в BIN.

**Comment by mikasoukhov** [comment]
https://github.com/StockSharp/Qsh2Bin/blob/master/MainWindow.xaml.cs#L401

Топик я закрываю. Если после конвертации нет ОИ, то проблема не в конвертации, а в данных.
